package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

func generate(root string) error {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedModule,
		Dir:  root,
	}
	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		return err
	}

	for _, pkg := range pkgs {
		if len(pkg.Errors) > 0 && pkg.Types == nil {
			continue
		}
		if pkg.PkgPath == "" || strings.Contains(pkg.PkgPath, "vendor") {
			continue
		}
		if strings.HasSuffix(pkg.PkgPath, "/cmd/reset") {
			continue
		}

		structs := findResetStructs(pkg)
		if len(structs) == 0 {
			continue
		}

		dir := filepath.Dir(pkg.GoFiles[0])
		out := filepath.Join(dir, "reset.gen.go")
		names := make(map[string]bool, len(structs))
		for _, s := range structs {
			names[s.name] = true
		}
		src, err := renderFile(pkg, structs, names)
		if err != nil {
			return fmt.Errorf("%s: %w", pkg.PkgPath, err)
		}
		formatted, err := format.Source(src)
		if err != nil {
			return fmt.Errorf("%s: format: %w", pkg.PkgPath, err)
		}
		if err := os.WriteFile(out, formatted, 0o644); err != nil {
			return err
		}
	}
	return nil
}

type resetStruct struct {
	name string
	typ  *types.Struct
}

func findResetStructs(pkg *packages.Package) []resetStruct {
	var out []resetStruct
	seen := make(map[string]bool)

	for _, file := range pkg.Syntax {
		if isTestFile(pkg, file) {
			continue
		}
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			if !hasGenerateReset(gen.Doc) {
				continue
			}
			for _, spec := range gen.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				if _, ok := ts.Type.(*ast.StructType); !ok {
					continue
				}
				name := ts.Name.Name
				if seen[name] {
					continue
				}
				seen[name] = true
				obj := pkg.TypesInfo.Defs[ts.Name]
				if obj == nil {
					continue
				}
				t := obj.Type().Underlying()
				str, ok := t.(*types.Struct)
				if !ok {
					continue
				}
				out = append(out, resetStruct{name: name, typ: str})
			}
		}
	}
	return out
}

func isTestFile(pkg *packages.Package, file *ast.File) bool {
	pos := pkg.Fset.Position(file.Pos())
	return strings.HasSuffix(pos.Filename, "_test.go")
}

func hasGenerateReset(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		if strings.Contains(c.Text, "generate:reset") {
			return true
		}
	}
	return false
}

func renderFile(pkg *packages.Package, structs []resetStruct, resetNames map[string]bool) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by cmd/reset; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg.Name)
	for _, s := range structs {
		if err := renderMethod(&b, pkg, s, resetNames); err != nil {
			return nil, err
		}
		b.WriteByte('\n')
	}
	return b.Bytes(), nil
}

func renderMethod(b *bytes.Buffer, pkg *packages.Package, s resetStruct, resetNames map[string]bool) error {
	recv := recvVar(s.name)
	fmt.Fprintf(b, "func (%s *%s) Reset() {\n", recv, s.name)
	fmt.Fprintf(b, "\tif %s == nil {\n", recv)
	fmt.Fprintf(b, "\t\treturn\n")
	fmt.Fprintf(b, "\t}\n")
	for i := 0; i < s.typ.NumFields(); i++ {
		field := s.typ.Field(i)
		lhs := recv + "." + field.Name()
		stmts := resetStmts(pkg, lhs, field.Type(), resetNames)
		for _, st := range stmts {
			fmt.Fprintf(b, "\t%s\n", st)
		}
	}
	fmt.Fprintf(b, "}\n")
	return nil
}

func recvVar(typeName string) string {
	if typeName == "" {
		return "v"
	}
	return strings.ToLower(string(typeName[0])) + "s"
}

func resetStmts(pkg *packages.Package, lhs string, typ types.Type, resetNames map[string]bool) []string {
	if named, ok := typ.(*types.Named); ok {
		if resetNames[named.Obj().Name()] || hasResetMethod(typ) {
			return []string{lhs + ".Reset()"}
		}
		return resetStmts(pkg, lhs, named.Underlying(), resetNames)
	}

	switch t := typ.Underlying().(type) {
	case *types.Basic:
		return []string{lhs + " = " + zeroLiteral(t)}
	case *types.Slice:
		return []string{lhs + " = " + lhs + "[:0]"}
	case *types.Map:
		return []string{"clear(" + lhs + ")"}
	case *types.Pointer:
		elem := t.Elem()
		if pointerToResettable(elem, resetNames) {
			return []string{
				fmt.Sprintf("if %s != nil {", lhs),
				"\t" + lhs + ".Reset()",
				"}",
			}
		}
		if hasResetMethod(elem) {
			return []string{
				fmt.Sprintf("if resetter, ok := %s.(interface{ Reset() }); ok && %s != nil {", lhs, lhs),
				"\tresetter.Reset()",
				"}",
			}
		}
		inner := resetStmts(pkg, "*"+lhs, elem, resetNames)
		block := append([]string{fmt.Sprintf("if %s != nil {", lhs)}, indentBlock(inner)...)
		block = append(block, "}")
		return block
	case *types.Struct:
		if hasResetMethod(typ) {
			return []string{lhs + ".Reset()"}
		}
		return []string{lhs + " = " + typeString(pkg, typ) + "{}"}
	case *types.Interface, *types.Chan, *types.Signature:
		return []string{lhs + " = nil"}
	case *types.Array:
		return []string{lhs + " = " + typeString(pkg, typ) + "{}"}
	default:
		return []string{lhs + " = " + zeroForType(pkg, typ)}
	}
}

func indentBlock(stmts []string) []string {
	out := make([]string, len(stmts))
	for i, s := range stmts {
		out[i] = "\t" + s
	}
	return out
}

func pointerToResettable(elem types.Type, resetNames map[string]bool) bool {
	named, ok := elem.(*types.Named)
	if !ok {
		return false
	}
	return resetNames[named.Obj().Name()]
}

func hasResetMethod(typ types.Type) bool {
	if typ == nil {
		return false
	}
	for _, t := range []types.Type{typ, types.NewPointer(typ)} {
		mset := types.NewMethodSet(t)
		for i := 0; i < mset.Len(); i++ {
			sel := mset.At(i)
			if sel.Obj().Name() != "Reset" {
				continue
			}
			sig, ok := sel.Obj().Type().(*types.Signature)
			if !ok {
				continue
			}
			if sig.Params().Len() == 0 && sig.Results().Len() == 0 {
				return true
			}
		}
	}
	return false
}

func zeroLiteral(b *types.Basic) string {
	switch b.Kind() {
	case types.Bool:
		return "false"
	case types.String:
		return `""`
	case types.Int, types.Int8, types.Int16, types.Int32, types.Int64,
		types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64, types.Uintptr,
		types.Float32, types.Float64, types.Complex64, types.Complex128:
		return "0"
	case types.UnsafePointer:
		return "nil"
	default:
		return "0"
	}
}

func typeString(pkg *packages.Package, t types.Type) string {
	return types.TypeString(t, func(p *types.Package) string {
		if p != nil && p.Path() == pkg.PkgPath {
			return ""
		}
		if p == nil {
			return ""
		}
		return p.Name()
	})
}

func zeroForType(pkg *packages.Package, t types.Type) string {
	if b, ok := t.Underlying().(*types.Basic); ok {
		return zeroLiteral(b)
	}
	return typeString(pkg, t) + "{}"
}
