// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batch.go

package db

import (
	"context"
	"errors"
	"time"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const createUrlBatch = `-- name: CreateUrlBatch :batchexec
INSERT INTO urls (short_url, original_url, created_at, user_id, is_deleted)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUrlBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateUrlBatchParams struct {
	ShortUrl    string
	OriginalUrl string
	CreatedAt   time.Time
	UserID      string
	IsDeleted   bool
}

func (q *Queries) CreateUrlBatch(ctx context.Context, arg []CreateUrlBatchParams) *CreateUrlBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ShortUrl,
			a.OriginalUrl,
			a.CreatedAt,
			a.UserID,
			a.IsDeleted,
		}
		batch.Queue(createUrlBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateUrlBatchBatchResults{br, len(arg), false}
}

func (b *CreateUrlBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateUrlBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
