// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Url struct {
	ShortUrl    string
	OriginalUrl string
	CreatedAt   time.Time
	UserID      string
	IsDeleted   bool
}
