// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CountURLs(ctx context.Context) (int32, error)
	CountUsers(ctx context.Context) (int32, error)
	CreateUrl(ctx context.Context, arg CreateUrlParams) error
	CreateUrlBatch(ctx context.Context, arg []CreateUrlBatchParams) *CreateUrlBatchBatchResults
	GetByOriginalURL(ctx context.Context, originalUrl string) (Url, error)
	GetByShortURL(ctx context.Context, shortUrl string) (Url, error)
	GetByUserID(ctx context.Context, userID string) ([]Url, error)
	MarkDeletedByShortURLs(ctx context.Context, arg MarkDeletedByShortURLsParams) error
}

var _ Querier = (*Queries)(nil)
