// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: urls.sql

package db

import (
	"context"
	"time"
)

const countURLs = `-- name: CountURLs :one
SELECT COUNT(*)::int FROM urls WHERE is_deleted = false
`

func (q *Queries) CountURLs(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countURLs)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(DISTINCT user_id)::int FROM urls WHERE is_deleted = false AND user_id <> ''
`

func (q *Queries) CountUsers(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createUrl = `-- name: CreateUrl :exec
INSERT INTO urls (short_url, original_url, created_at, user_id, is_deleted)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUrlParams struct {
	ShortUrl    string
	OriginalUrl string
	CreatedAt   time.Time
	UserID      string
	IsDeleted   bool
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) error {
	_, err := q.db.Exec(ctx, createUrl,
		arg.ShortUrl,
		arg.OriginalUrl,
		arg.CreatedAt,
		arg.UserID,
		arg.IsDeleted,
	)
	return err
}

const getByOriginalURL = `-- name: GetByOriginalURL :one
SELECT short_url, original_url, created_at, user_id, is_deleted
FROM urls
WHERE original_url = $1 AND is_deleted = false
`

func (q *Queries) GetByOriginalURL(ctx context.Context, originalUrl string) (Url, error) {
	row := q.db.QueryRow(ctx, getByOriginalURL, originalUrl)
	var i Url
	err := row.Scan(
		&i.ShortUrl,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.UserID,
		&i.IsDeleted,
	)
	return i, err
}

const getByShortURL = `-- name: GetByShortURL :one
SELECT short_url, original_url, created_at, user_id, is_deleted
FROM urls
WHERE short_url = $1
`

func (q *Queries) GetByShortURL(ctx context.Context, shortUrl string) (Url, error) {
	row := q.db.QueryRow(ctx, getByShortURL, shortUrl)
	var i Url
	err := row.Scan(
		&i.ShortUrl,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.UserID,
		&i.IsDeleted,
	)
	return i, err
}

const getByUserID = `-- name: GetByUserID :many
SELECT short_url, original_url, created_at, user_id, is_deleted
FROM urls
WHERE user_id = $1 AND is_deleted = false
`

func (q *Queries) GetByUserID(ctx context.Context, userID string) ([]Url, error) {
	rows, err := q.db.Query(ctx, getByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ShortUrl,
			&i.OriginalUrl,
			&i.CreatedAt,
			&i.UserID,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeletedByShortURLs = `-- name: MarkDeletedByShortURLs :exec
UPDATE urls
SET is_deleted = true
WHERE user_id = $1 AND short_url = ANY($2::text[])
`

type MarkDeletedByShortURLsParams struct {
	UserID  string
	Column2 []string
}

func (q *Queries) MarkDeletedByShortURLs(ctx context.Context, arg MarkDeletedByShortURLsParams) error {
	_, err := q.db.Exec(ctx, markDeletedByShortURLs, arg.UserID, arg.Column2)
	return err
}
